description: "My comparison"

prompts:
  - 'Solve this riddle: {{riddle}}'

providers:
  - ollama:chat:phi3
  # - ollama:chat:phi3:medium
  - ollama:chat:llama2
  # - ollama:chat:llama3
  # - ollama:chat:llama3.1
  # - ollama:chat:mistral
  # - ollama:chat:mistral:v0.2
  - ollama:chat:gemma2
  - id: azureopenai:chat:gpt-4o-mini
    config:
      apiHost: 'cog-zolnwmeatemto.openai.azure.com'
  - id: azureopenai:chat:gpt-35-turbo
    config:
      apiHost: 'cog-zolnwmeatemto.openai.azure.com'

tests:
  - vars:
      riddle: 'I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?'
  - vars:
      riddle: 'You see a boat filled with people. It has not sunk, but when you look again you donâ€™t see a single person on the boat. Why?'
  - vars:
      riddle: 'The more of this there is, the less you see. What is it?'

